import Head from 'next/head'
import { TeliaTextInput } from '@teliads/components/react'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <TeliaTextInput
        id='searchTerm'
        name='searchTerm'
        type='text'
        inputmode='text'
        label={'Search for device'}
        onInput={() => console.log('adsadas')}
        className='w-[23.75rem]'
      />
    </>
  )
}
